### ISSUE TITLE
目玉を作る

### ISSUE THREAD

**Issue by AyaEbata** [java-women/cocorobo-pet#13]
### フロー
1. Javaアプリケーション経由で、ココロボのリクエスト（感情）を取得（デフォルト10秒毎）
2. JSON形式で取得した値によって目玉画像を出し分けて表示する
### 時間があったら
- 目玉APIのパス、 `toko` 、 `seiko` を変更できるようにする（menu画面から値を渡す想定）
- 瞬きさせたいな。。。
### 目玉の種類
- 普通の顔 normal
- 待って〜！って顔 mattee
- 置いてかれた、しょぼーん shoboon
- 喜び waai
- ムキーッ！ mukii
- キラーン kiraan
- 目がハート sukii

アルファベットのものがJSONで渡ってくる認識です。
他にも良さげなのありましたら、是非意見下さい〜！
### JSON形式

```
{
    "result": 実行結果(boolean), 
    "feel": 目玉の種類(String)
}
```
#### 【Sample】

``` json
{
    "result": true, 
    "feel": "dere"
}
```

**Comment by omame1986** [comment]
・Javaアプリケーション経由で、ココロボのリクエスト（感情）を取得
・目玉の画像作成・表示

**Comment by AyaEbata** [comment]
遠くに行ってしまった時に悲しい顔になる、とか、
そういう感情もコントロールできるものも作っておく

**Comment by omame1986** [comment]
データのインターフェース

**Comment by AyaEbata** [comment]
顔の種類
- 待って〜！って顔
- 置いてかれた、しょぼーん
- 喜び
- デレデレ
- ツン

プラス、何個か

文字列で渡してもらう。JSONで。
dere, tun, shoboon, waai, mattee

**Comment by AyaEbata** [comment]
APIを取得しまくる
設定で何秒で感情変えるかできるように（デフォルト10秒とか

**Comment by AyaEbata** [comment]
上記の詳細についてまとめて書き直しました〜！
https://github.com/java-women/cocorobo-pet/issues/13#issue-176228492

@erk5 さん
ココロボから渡ってくるJSONの形式はこんな感じの認識でよろしいですか？（普通がわからない…

**Comment by mahya8585** [comment]
@AyaEbata 良いと思います>JSON
細かいこと言うと、JSONのパラメータ名はダブルコーテーションで囲んでね！

インタフェースのやり取りをする時は型も一緒に連絡しておく(もしくはサンプルに値を入れておく）といいと思います。

```
{
    "result": true, 
    "feel": "dere"
}
```

とか書いてあげるとbooleanなのかStringなのか分かりやすく良いですね

LGTM.

**Comment by AyaEbata** [comment]
@mahya8585 さん
確認ありがとうございます！
書き方を修正し、サンプルを付け加えてみました！

**Comment by erk5** [comment]
@AyaEbata 
サンプルインタフェースを作成しました。
#36 を確認お願いします！

**Comment by AyaEbata** [comment]
@erk5 さん
確認しました！大丈夫そうです。ありがとうございます！
`toko` の部分はアプリ側の設定で変更可能の方が良さげですか？

**Comment by erk5** [comment]
@AyaEbata
変えられるとbetterだけど、
余裕なければ固定で良いですよー

**Comment by AyaEbata** [comment]
@erk5 さん
かしこまりです！
時間があったらタスクに一応入れておきます！

**Comment by AyaEbata** [comment]
担当者がわからないので、とりあえず @erk5 さん宛で！

JSONで送ってくる目玉の種類、変えても平気ですか？
ツンとデレがとても目だけでは現しづらい気がしますので、ムキーッ！となんか別の顔(思いついてない)はどうですか？

**Comment by erk5** [comment]
@AyaEbata 
まだCocoroboから取得した感情値でどの目玉の種類を返すかのロジックは作っていないはずなので、丈夫だと思います。
目玉の種類を確定して列挙しておいてもらえればOKです。

**Comment by AyaEbata** [comment]
@erk5 さん (むしろれいかさん？もずく？

では、それなりに変えて上記のJSONの値を変更します。

**Comment by AyaEbata** [comment]
#41 でマージされたのでクローズします。
