### ISSUE TITLE
menu画面の作成

### ISSUE THREAD

**Issue by AyaEbata** [java-women/cocorobo-pet#23]

**Comment by omame1986** [comment]
・目玉ボタン
・飼い主撮影ボタン

**Comment by AyaEbata** [comment]
早くおわった方がやる

**Comment by omame1986** [comment]
感情を5秒~10秒ごとに変化の設定

**Comment by AyaEbata** [comment]
> ペットモード時に誰についていくか決定させる(userIdの入力)

https://github.com/java-women/cocorobo-pet/issues/33#issuecomment-246319353

menu画面？？？とりあえずAndroid側でやると思われ。

**Comment by mahya8585** [comment]
拾ってくれてありがと。どのマスターデータを教師データにするのか決めないとダメなんだったっていう発想から生まれた処理です。
詳細わからなければハングアウトで

**Comment by AyaEbata** [comment]
#36 
時間があれば、目玉APIのパス、 `toko` 、 `seiko` を変更できるようにする

**Comment by AyaEbata** [comment]
#36 
時間があれば、東子の目玉 `toko` 、西子の目玉 `seiko` をmenu画面で変更できるようにする
https://github.com/java-women/cocorobo-pet/issues/13#issuecomment-246864722

**Comment by AyaEbata** [comment]
@omame1986 さん
menu画面の作成やりますねー。
（多分現時点ではダサいボタンをいい感じにするだけだと思うので

**Comment by AyaEbata** [comment]
#49 にてマージされたので、クローズします。
