### ISSUE TITLE
CognitiveAPIを立てる

### ISSUE THREAD

**Issue by mppppp** [java-women/cocorobo-pet#7]

**Comment by mahya8585** [comment]
## ゴール
- 初期設定
- サンプルコードの作成

**Comment by mahya8585** [comment]
試しに↓と今のアカウントの写真を比較してみたら悲しい結果になった。

![まーや1](https://media.licdn.com/mpr/mpr/shrinknp_200_200/AAEAAQAAAAAAAAltAAAAJGI3NzdhOWY3LWExYjctNDFmZC05NjdmLWRjYmIxZWJlMmU0MQ.jpg)

```
{
  "isIdentical": true,
  "confidence": 0.51637
}
```

同一人物だけど類似度0.5。。。
こんなもんなのかな・・・
まぁとりあえずisIdenticalの値で判定すればよさそう

**Comment by mahya8585** [comment]
なぜfaceLandmarkが取得できないのかは謎だ・・・
私の顔がのっぺらいせいか・・・

**Comment by mahya8585** [comment]
https://github.com/java-women/cocorobo-pet/tree/serverEnv/serverEnv/cognitiveSample
にサンプルアプリ開発中

**Comment by mahya8585** [comment]
https://github.com/java-women/cocorobo-pet/tree/master/serverEnv/cognitiveSample
サンプル作ったのに挙げてませんでした・・・
そして会社昼休みなうなのでブラウザからがっつりあげました・・・疲れた・・・

そしてAPIkeyうっかりコミットしました。。。
※今はこのAPIKeyは削除して新しいものを取得しています。
